routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');

Route::get('/', [
	'uses' => 'BlogController@index',
	'as' => 'blog',
]);

Route::get('/berita/{postings}', [
	'uses' => 'BlogController@tampil',
	'as' => 'blog.tampil',
]);

Route::get('/category/{category}', [
	'uses' => 'BlogController@kategori',
	'as' => 'category',
]);

Route::get('/berita', [
	'uses' => 'BlogController@berita',
	'as' => 'blog.berita',
]);

Route::get('/author/{author}', [
	'uses' => 'BlogController@author',
	'as' => 'author',
]);

Route::put('/backend/blog/restore/{blog}', [
	'as' => 'backend.blog.restore',
	'uses' => 'Backend\BlogController@restore',
]);

Route::delete('/backend/blog/force-destroy/{blog}', [
	'as' => 'backend.blog.force-destroy',
	'uses' => 'Backend\BlogController@forceDestroy',
]);

Route::put('/backend/prestasi/restore/{prestasi}', [
	'as' => 'backend.prestasi.restore',
	'uses' => 'Backend\PrestasiController@restore',
]);

Route::delete('/backend/prestasi/force-destroy/{prestasi}', [
	'as' => 'backend.prestasi.force-destroy',
	'uses' => 'Backend\PrestasiController@forceDestroy',
]);

Route::resource('/backend/blog', 'Backend\BlogController');

Route::resource('/backend/prestasi', 'Backend\PrestasiController');

Route::resource('/backend/categories', 'Backend\CategoriesController');

Route::resource('/backend/users', 'Backend\UsersController');

Route::resource('/backend/jurusan', 'Backend\JurusanController');

Route::resource('/backend/profil', 'Backend\ProfilController');

app/Postings.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;

class Postings extends Model
{
    use SoftDeletes;
    
	protected $dates = ['published_at'];
    protected $fillable = ['title','slug','excerpt','body','published_at','category_id', 'image'];

	public function Author()
	{
		return $this->belongsTo(User::class);
	}

	public function Category()
	{
		return $this->belongsTo(Category::class);
	}

    public function getImageUrlAttribute($value)
    {
    	$gambarUrl = "";

    	if(!is_null($this->image)){
            $directory = config('cms.image.directory');
    		$gambarPath = public_path(). "/{$directory}/" . $this->image;
    		if(file_exists($gambarPath)){
    			$gambarUrl = asset("{$directory}/" . $this->image);
    		}
    	}

    	return $gambarUrl;
    }

    public function getImageThumbUrlAttribute($value)
    {
        
        $gambarUrl = "";

        if(!is_null($this->image)){
            $directory = config('cms.image.directory');
            $ekstensi = substr(strchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ekstensi}", "_thumb.{$ekstensi}", $this->image);
            $gambarPath = public_path(). "/{$directory}/" . $thumbnail;
            if(file_exists($gambarPath)){
                $gambarUrl = asset("{$directory}/" . $thumbnail);
            }
        }

        return $gambarUrl;
    }

    public function getDateAttribute($value)
    {
    	return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function scopeLatestFirst()
    {
    	return $this->orderBy('published_at', 'DESC');
    }

    public function scopePopular()
    {
        return $this->orderBy('view_count', 'DESC');
    }

    public function scopePublished()
    {
    	return $this->where("published_at", "<=", Carbon::now());
    }

    public function getBodyHtmlAttribute($value)
    {
    	return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }

    public function getExcerptHtmlAttribute($value)
    {
    	return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
    }

    public function dateFormatted($showTimes = false)
    {
        $format = "d/m/Y";
        if($showTimes) $format = $format . " H:i:s";
        return $this->created_at->format($format);
    }

    public function publicationLabel()
    {
        if(! $this->published_at){
            return '<span class="badge badge-warning">Draft</span>';
        }elseif($this->published_at && $this->published_at->isFuture()){
            return '<span class="badge badge-info">Terjadwal</span>';
        }else{
            return '<span class="badge badge-success">Dipublikasikan</span>';
        }
    }

    public function setPublishedAtAttribute($value)
    {
        $this->attributes['published_at'] = $value ?: NULL;
    }

    public function scopeScheduled($query)
    {
        return $query->where("published_at", ">", Carbon::now());   
    }

    public function scopeDraft($query)
    {
        return $query->whereNull("published_at");
    }

}

app/Profil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;

class Profil extends Model
{
    public $table = 'profil';
    protected $fillable = ['namasekolah','alamat','telp','sejarah','namaheader','gambarbg','gambarbg2','gambarbg3','logo','motto','visi','misi','fax','email'];

    public function getLogoUrlAttribute($value)
    {
    	$gambarUrl = "";

    	if(!is_null($this->logo)){
            $directory = config('cms.image.directory');
    		$gambarPath = public_path(). "/{$directory}/" . $this->logo;
    		if(file_exists($gambarPath)){
    			$gambarUrl = asset("{$directory}/" . $this->logo);
    		}
    	}

    	return $gambarUrl;
    }

    public function getGambarBgAUrlAttribute($value)
    {
        $gambarUrl = "";

        if(!is_null($this->gambarbg)){
            $directory = config('cms.image.directory');
            $gambarPath = public_path(). "/{$directory}/" . $this->gambarbg;
            if(file_exists($gambarPath)){
                $gambarUrl = asset("{$directory}/" . $this->gambarbg);
            }
        }

        return $gambarUrl;
    }

    public function getGambarBgBUrlAttribute($value)
    {
        $gambarUrl = "";

        if(!is_null($this->gambarbg2)){
            $directory = config('cms.image.directory');
            $gambarPath = public_path(). "/{$directory}/" . $this->gambarbg2;
            if(file_exists($gambarPath)){
                $gambarUrl = asset("{$directory}/" . $this->gambarbg2);
            }
        }

        return $gambarUrl;
    }

    public function getGambarBgCUrlAttribute($value)
    {
        $gambarUrl = "";

        if(!is_null($this->gambarbg3)){
            $directory = config('cms.image.directory');
            $gambarPath = public_path(). "/{$directory}/" . $this->gambarbg3;
            if(file_exists($gambarPath)){
                $gambarUrl = asset("{$directory}/" . $this->gambarbg3);
            }
        }

        return $gambarUrl;
    }

    public function getDateAttribute($value)
    {
        return is_null($this->created_at) ? '' : $this->created_at->diffForHumans();
    }
}

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SANBERCODE | Sekolah Santuy</title>
    
    <!-- page css -->
    <link href="{{ asset('backend/css/pages/login-register-lock.css') }}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ asset('backend/css/style.min.css') }}" rel="stylesheet">
    
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="skin-default card-no-border">
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper">
        @yield('konten')
    </section>
    
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{ asset('backend/assets/node_modules/jquery/jquery-3.2.1.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ asset('backend/assets/node_modules/popper/popper.min.js') }}"></script>
    <script src="{{ asset('backend/assets/node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!--Custom JavaScript -->
    <script type="text/javascript">
        
    </script>
    
</body>

</html>

resources/views/layout/frontend.blade.php
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <meta name="description" content="Website Generator Description">
  
  
  <title>@yield('title', 'SANBERCODE | Sekolah Santuy')</title>
  <link rel="stylesheet" href="{{ asset('frontend/assets/web/assets/mobirise-icons/mobirise-icons.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/bootstrap/css/bootstrap-grid.min.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/bootstrap/css/bootstrap-reboot.min.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/socicon/css/styles.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/dropdown/css/style.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/tether/tether.min.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/animatecss/animate.min.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/theme/css/style.css') }}">
  <link rel="preload" as="style" href="{{ asset('frontend/assets/mobirise/css/mbr-additional.css') }}">
  <link rel="stylesheet" href="{{ asset('frontend/assets/mobirise/css/mbr-additional.css') }}" type="text/css">
  
  
  
</head>
<body>
<section class="menu cid-s42m5yqLZm" once="menu" id="menu1-a">
   
    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-toggleable-sm bg-color transparent">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{{ route('blog') }}">
                        @foreach($profil as $prof)
                        @if($prof->logo != '')
                        <img src="{{ $prof->logo_url }}" alt="" title="" style="height: 8rem;">
                        @else
                        <strong>LOGO</strong>
                        @endif
                        @endforeach
                    </a>
                </span>
                
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{{ route('blog') }}">
                        <span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{{ route('blog.berita') }}">
                        <span class="mbri-globe mbr-iconfont mbr-iconfont-btn"></span>
                        Blog
                    </a>
                </li>
            </ul>            
        </div>
    </nav>
</section>

<section class="mbr-section content5 cid-s44mk81tRB mbr-parallax-background" id="content5-12">
   
    <div class="mbr-overlay" style="opacity: 0.2; background-color: rgb(35, 35, 35);">
    </div>

    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">
                    BERITA TERBARU
                </h2>                
            </div>
        </div>
    </div>

</section>

@yield('konten')
@yield('kontenblog')
<section class="cid-s43RaeFXRA" id="footer1-10">

    <div class="container">
        <div class="media-container-row content text-white">
            <div class="col-12 col-md-3">
                <div class="media-wrap">
                    <a href="{{ route('blog') }}">
                        @foreach($profil as $prof)
                        @if($prof->logo != '')
                        <img src="{{ $prof->logo_url }}" alt="" title="" style="height: 8rem;">
                        @else
                        <strong>LOGO</strong>
                        @endif
                        @endforeach
                    </a>
                </div>
            </div>
            @foreach($profil as $prof)
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
                <h5 class="pb-3">
                    Sejarah Singkat</h5>
                <p class="mbr-text">
                    {{ $prof->sejarah }}
                </p>
            </div>
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
                <h5 class="pb-3">
                    Kontak</h5>
                <p class="mbr-text">
                    Email: {{ $prof->email != "" ? $prof->email : "-" }}
                    <br>Telp: {{ $prof->telp != "" ? $prof->telp : "-" }}
                    <br>Fax: {{ $prof->fax != "" ? $prof->fax : "-" }}
                </p>
            </div>
            @endforeach
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
                <h5 class="pb-3">Daftar Jurusan</h5>
                <p class="mbr-text">
                    @foreach($daftarjurusan as $jurusan)
                    <a class="text-primary" href="#">{{ $jurusan->nama }}</a>
                    <br><br>
                    @endforeach
                </p>
            </div>
        </div>
        <div class="footer-lower">
            <div class="media-container-row">
                <div class="col-sm-12">
                    <hr>
                </div>
            </div>
            <div class="media-container-row mbr-white">
                <div class="col-sm-6 copyright">
                    <p class="mbr-text mbr-fonts-style display-7">
                        © Copyright 2020
                    </p>
                </div>
                <div class="col-md-6">
                    
                </div>
            </div>
        </div>
    </div>
</section>


  <script src="{{ asset('frontend/assets/web/assets/jquery/jquery.min.js') }}"></script>
  <script src="{{ asset('frontend/assets/popper/popper.min.js') }}"></script>
  <script src="{{ asset('frontend/assets/bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('frontend/assets/smoothscroll/smooth-scroll.js') }}"></script>
  <script src="{{ asset('frontend/assets/dropdown/js/nav-dropdown.js') }}"></script>
  <script src="{{ asset('frontend/assets/dropdown/js/navbar-dropdown.js') }}"></script>
  <script src="{{ asset('frontend/assets/tether/tether.min.js') }}"></script>
  <script src="{{ asset('frontend/assets/viewportchecker/jquery.viewportchecker.js') }}"></script>
  <script src="{{ asset('frontend/assets/parallax/jarallax.min.js') }}"></script>
  <script src="{{ asset('frontend/assets/mbr-popup-btns/mbr-popup-btns.js') }}"></script>
  <script src="{{ asset('frontend/assets/touchswipe/jquery.touch-swipe.min.js') }}"></script>
  <script src="{{ asset('frontend/assets/theme/js/script.js') }}"></script>
  
  
  <input name="animation" type="hidden">
  </body>
</html>

resources/views/layout/sidebar.blade.php
<div class="col-lg-4">

  <div class="sidebar">

    <!--<h3 class="sidebar-title">Search</h3>
    <div class="sidebar-item search-form">
      <form action="">
        <input type="text">
        <button type="submit"><i class="icofont-search"></i></button>
      </form>

    </div>--><!-- End sidebar search formn-->

    <h3 class="sidebar-title">Kategori</h3>
    <div class="sidebar-item categories">
      <ul>
        @foreach($categories as $cat)
        <li><a href="{{ route('category', $cat->slug) }}">{{ $cat->title }} <span>{{ $cat->posts->count() }}</span></a></li>
        @endforeach
      </ul>

    </div><!-- End sidebar categories-->

    <h3 class="sidebar-title">Berita Lainya</h3>

    <div class="sidebar-item recent-posts">

      @foreach($popularPosts as $post)
      <div class="post-item clearfix">
        @if($post->image_url)
        <img src="{{ $post->image_url }}" alt="">
        @else
        <img src="{{ asset('frontend/assets/img/berita-bg.jpg') }}" alt="">
        @endif
        <h4><a href="{{ route('blog.tampil', $post->slug) }}">{{ $post->title }}</a></h4>
        <time datetime="{{ $post->date }}">{{ $post->date }}</time>
      </div>
      @endforeach

    </div><!-- End sidebar recent posts-->

  </div><!-- End sidebar -->

</div><!-- End blog sidebar -->