routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');

Route::get('/', [
	'uses' => 'BlogController@index',
	'as' => 'blog',
]);

Route::get('/berita/{postings}', [
	'uses' => 'BlogController@tampil',
	'as' => 'blog.tampil',
]);

Route::get('/category/{category}', [
	'uses' => 'BlogController@kategori',
	'as' => 'category',
]);

Route::get('/berita', [
	'uses' => 'BlogController@berita',
	'as' => 'blog.berita',
]);

Route::get('/author/{author}', [
	'uses' => 'BlogController@author',
	'as' => 'author',
]);

Route::put('/backend/blog/restore/{blog}', [
	'as' => 'backend.blog.restore',
	'uses' => 'Backend\BlogController@restore',
]);

Route::delete('/backend/blog/force-destroy/{blog}', [
	'as' => 'backend.blog.force-destroy',
	'uses' => 'Backend\BlogController@forceDestroy',
]);

Route::put('/backend/prestasi/restore/{prestasi}', [
	'as' => 'backend.prestasi.restore',
	'uses' => 'Backend\PrestasiController@restore',
]);

Route::delete('/backend/prestasi/force-destroy/{prestasi}', [
	'as' => 'backend.prestasi.force-destroy',
	'uses' => 'Backend\PrestasiController@forceDestroy',
]);

Route::resource('/backend/blog', 'Backend\BlogController');

Route::resource('/backend/prestasi', 'Backend\PrestasiController');

Route::resource('/backend/categories', 'Backend\CategoriesController');

Route::resource('/backend/users', 'Backend\UsersController');

Route::resource('/backend/jurusan', 'Backend\JurusanController');

Route::resource('/backend/profil', 'Backend\ProfilController');

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check-permission');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Postings;
use Intervention\Image\Facades\Image;

class BlogController extends BackendController
{
    protected $uploadPath;

    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = public_path(config('cms.image.directory'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $postings = Postings::with('category')->with('author')->latestFirst()->get();

        $postingsTrash = Postings::with('category')->with('author')->latestFirst()->onlyTrashed()->get();

        $postingsPublished = Postings::with('category')->with('author')->latestFirst()->published()->get();

        $postingsDrafted = Postings::with('category')->with('author')->latestFirst()->draft()->get();

        $postingsScheduled = Postings::with('category')->with('author')->latestFirst()->scheduled()->get();

        return view("backend.blog.index", compact('postings', 'postingsTrash','postingsScheduled','postingsDrafted','postingsPublished'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Postings $postings)
    {
        return view("backend.blog.create", compact('postings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\PostRequest $request)
    {
        $data = $this->handleRequest($request);

        $request->user()->posts()->create($data);

        $notification = array(
            'message' => 'Data berhasil disimpan', 
            'alert-type' => 'success'
        );

        return redirect('/backend/blog')->with($notification);
    }

    public function handleRequest($request)
    {
        $data = $request->all();

        if($request->hasFile('image'))
        {
            $width = config('cms.image.thumbnail.width');
            $height = config('cms.image.thumbnail.height');
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $destination = $this->uploadPath;

            $successUploaded = $image->move($destination, $fileName);

            if($successUploaded)
            {
                $ekstensi = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$ekstensi}", "_thumbnail.{$ekstensi}", $fileName);
                Image::make($destination . '/' . $fileName)->resize($width, $height)->save($destination . '/' . $thumbnail);
            }

            $data['image'] = $fileName;
        }

        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $postings = Postings::findOrFail($id);
        return view("backend.blog.edit", compact("postings"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\PostRequest $request, $id)
    {
        $postings = Postings::findOrFail($id);
        $gambarLama = $postings->image;
        $data = $this->handleRequest($request);
        $postings->update($data);

        if($gambarLama !== $postings->image){
            $this->removeImage($gambarLama);
        }

        $notification = array(
            'message' => 'Data berhasil diubah', 
            'alert-type' => 'success'
        );

        return redirect('/backend/blog')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Postings::findOrFail($id)->delete();

        $notification = array(
            'message' => $id, 
            'alert-type' => 'trash-message',
        );

        return redirect()->back()->with($notification);
    }

    public function restore($id)
    {
        $postings = Postings::withTrashed()->findOrFail($id);
        $postings->restore();

        $notification = array(
            'message' => 'Data berhasil di kembalikan', 
            'alert-type' => 'success',
        );

        return redirect()->back()->with($notification);
    }

    public function forceDestroy($id)
    {
        $postings = Postings::withTrashed()->findOrFail($id);
        $postings->forceDelete();

        $this->removeImage($postings->image);

        $notification = array(
            'message' => 'Data berhasil di hapus permanen', 
            'alert-type' => 'success',
        );

        return redirect()->back()->with($notification);
    }

    public function removeImage($image)
    {
        if(!empty($image))
        {
            $imagePath = $this->uploadPath . '/' . $image;
            $ekstensi = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ekstensi}", "_thumbnail.{$ekstensi}", $image);
            $thumbnailPath = $this->uploadPath . '/' .$thumbnail;

            if(file_exists($imagePath)) unlink($imagePath);
            if(file_exists($thumbnailPath)) unlink($thumbnailPath);
        }
    }
}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Category;
use App\Postings;

class CategoriesController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('posts')->orderBy('title')->get();

        return view("backend.categories.index", compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category();
        return view("backend.categories.create", compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\CategoryStoreRequest $request)
    {
        Category::create($request->all());

        $notification = array(
            'message' => 'Data berhasil disimpan',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view("backend.categories.edit", compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\CategoryUpdateRequest $request, $id)
    {
        Category::findOrFail($id)->update($request->all());

        $notification = array(
            'message' => 'Data berhasil diubah',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\CategoryDestroyRequest $request, $id)
    {
        $category = Category::findOrFail($id);
        Postings::withTrashed()->where('category_id', $id)->update(['category_id' => config('cms.default_category_idnya') ]);
        $category->delete();

        $notification = array(
            'message' => 'Data berhasil di hapus',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\User;
use App\Postings;
use App\Category;
use App\Prestasi;

class HomeController extends BackendController
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
    	$userCount = User::all()->count();
    	$postingsCount = Postings::all()->count();
    	$kategoriCount = Category::all()->count();
    	$prestasiCount = Prestasi::all()->count();

        return view('backend.home', compact('userCount', 'postingsCount', 'kategoriCount', 'prestasiCount'));
    }
}

app/Http/Controllers/Backend/JurusanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Jurusan;

class JurusanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $daftarjurusan = Jurusan::all();

        return view("backend.jurusan.index", compact('daftarjurusan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $daftarjurusan = new Jurusan();
        return view("backend.jurusan.create", compact('daftarjurusan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\JurusanRequest $request)
    {
        Jurusan::create($request->all());

        $notification = array(
            'message' => 'Data berhasil disimpan',
            'alert-type' => 'success'
        );

        return redirect("/backend/jurusan")->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $daftarjurusan = Jurusan::findOrFail($id);

        return view("backend.jurusan.edit", compact('daftarjurusan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\JurusanRequest $request, $id)
    {
        Jurusan::findOrFail($id)->update($request->all());

        $notification = array(
            'message' => 'Data berhasil diubah',
            'alert-type' => 'success'
        );

        return redirect("/backend/jurusan")->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Jurusan::findOrFail($id)->delete();

        $notification = array(
            'message' => 'Data berhasil di hapus',
            'alert-type' => 'success'
        );

        return redirect()->back()->with($notification);
    }
}

resources/views/layout/backend/navbar.blade.php
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">
               
                <!--End Logo icon -->
                <!-- Logo text --><span>
                 <!-- dark Logo text -->
                 &nbsp;
                 <h4 class="dark-logo"><strong>KELOMPOK 8</strong></h4>
                 <!-- Light Logo text -->    
                 <h4 class="light-logo"><strong>KELOMPOK 8</strong></h4></span>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav mr-auto">
                <!-- This is  -->
                <li class="nav-item"> <a class="nav-link nav-toggler d-block d-md-none waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                <li class="nav-item"> <a class="nav-link sidebartoggler d-none d-lg-block d-md-block waves-effect waves-dark" href="javascript:void(0)"><i class="icon-menu"></i></a> </li>
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>

resources/views/layout/backend/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User Profile-->
        <div class="user-profile">
            <div class="user-pro-body">
                <div><img src="{{ asset('backend/assets/images/users/user.png') }}" alt="user-img" class="img-circle"></div>
                <div class="dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle u-dropdown link hide-menu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
                    <div class="dropdown-menu animated flipInY">
                        <!-- text-->
                        <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <i class="fas fa-power-off"></i> Keluar</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                        <!-- text-->
                    </div>
                </div>
            </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li> <a href="{{ url('/home') }}"><i class="icon-speedometer"></i><span class="hide-menu">Dashboard </span></a>
                </li>
                <li> <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="icon-pencil"></i><span class="hide-menu">Blog </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('blog.index') }}">Semua Postingan </a></li>
                        <li><a href="{{ route('blog.create') }}">Tambah Baru</a></li>
                    </ul>
                </li>
                <li> <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="icon-star"></i><span class="hide-menu">Prestasi </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('prestasi.index') }}">Semua Prestasi </a></li>
                        <li><a href="{{ route('prestasi.create') }}">Tambah Baru</a></li>
                    </ul>
                </li>
                
                @role(['admin','editor'])
                <li> <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="icon-pin"></i><span class="hide-menu">Kategori </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('categories.index') }}">Daftar Kategori </a></li>
                    </ul>
                </li>
                <li> <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="icon-wrench"></i><span class="hide-menu">Profil </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('profil.edit', 1) }}">Ubah</a></li>
                    </ul>
                </li>
                <li> <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="icon-directions"></i><span class="hide-menu">Jurusan </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('jurusan.index') }}">Semua Jurusan </a></li>
                        <li><a href="{{ route('jurusan.create') }}">Tambah Baru</a></li>
                    </ul>
                </li>
                @endrole
                <!--@role('admin')
                <li> <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="icon-people"></i><span class="hide-menu">User </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('users.index') }}">Daftar User </a></li>
                    </ul>
                </li>
                @endrole-->
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>