routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');

Route::get('/', [
	'uses' => 'BlogController@index',
	'as' => 'blog',
]);

Route::get('/berita/{postings}', [
	'uses' => 'BlogController@tampil',
	'as' => 'blog.tampil',
]);

Route::get('/category/{category}', [
	'uses' => 'BlogController@kategori',
	'as' => 'category',
]);

Route::get('/berita', [
	'uses' => 'BlogController@berita',
	'as' => 'blog.berita',
]);

Route::get('/author/{author}', [
	'uses' => 'BlogController@author',
	'as' => 'author',
]);

Route::put('/backend/blog/restore/{blog}', [
	'as' => 'backend.blog.restore',
	'uses' => 'Backend\BlogController@restore',
]);

Route::delete('/backend/blog/force-destroy/{blog}', [
	'as' => 'backend.blog.force-destroy',
	'uses' => 'Backend\BlogController@forceDestroy',
]);

Route::put('/backend/prestasi/restore/{prestasi}', [
	'as' => 'backend.prestasi.restore',
	'uses' => 'Backend\PrestasiController@restore',
]);

Route::delete('/backend/prestasi/force-destroy/{prestasi}', [
	'as' => 'backend.prestasi.force-destroy',
	'uses' => 'Backend\PrestasiController@forceDestroy',
]);

Route::resource('/backend/blog', 'Backend\BlogController');

Route::resource('/backend/prestasi', 'Backend\PrestasiController');

Route::resource('/backend/categories', 'Backend\CategoriesController');

Route::resource('/backend/users', 'Backend\UsersController');

Route::resource('/backend/jurusan', 'Backend\JurusanController');

Route::resource('/backend/profil', 'Backend\ProfilController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use GrahamCampbell\Markdown\Facades\Markdown;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;
    
    public $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','no_hp','alamat','slug','bio'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Postings::class, 'author_id');
    }

    public function prestasi()
    {
        return $this->hasMany(Prestasi::class, 'author_id');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getBioHtmlAttribute($value)
    {
        return $this->bio ? Markdown::convertToHtml(e($this->bio)) : NULL;
    }

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check-permission');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Postings;
use Intervention\Image\Facades\Image;

class BlogController extends BackendController
{
    protected $uploadPath;

    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = public_path(config('cms.image.directory'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $postings = Postings::with('category')->with('author')->latestFirst()->get();

        $postingsTrash = Postings::with('category')->with('author')->latestFirst()->onlyTrashed()->get();

        $postingsPublished = Postings::with('category')->with('author')->latestFirst()->published()->get();

        $postingsDrafted = Postings::with('category')->with('author')->latestFirst()->draft()->get();

        $postingsScheduled = Postings::with('category')->with('author')->latestFirst()->scheduled()->get();

        return view("backend.blog.index", compact('postings', 'postingsTrash','postingsScheduled','postingsDrafted','postingsPublished'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Postings $postings)
    {
        return view("backend.blog.create", compact('postings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\PostRequest $request)
    {
        $data = $this->handleRequest($request);

        $request->user()->posts()->create($data);

        $notification = array(
            'message' => 'Data berhasil disimpan', 
            'alert-type' => 'success'
        );

        return redirect('/backend/blog')->with($notification);
    }

    public function handleRequest($request)
    {
        $data = $request->all();

        if($request->hasFile('image'))
        {
            $width = config('cms.image.thumbnail.width');
            $height = config('cms.image.thumbnail.height');
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $destination = $this->uploadPath;

            $successUploaded = $image->move($destination, $fileName);

            if($successUploaded)
            {
                $ekstensi = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$ekstensi}", "_thumbnail.{$ekstensi}", $fileName);
                Image::make($destination . '/' . $fileName)->resize($width, $height)->save($destination . '/' . $thumbnail);
            }

            $data['image'] = $fileName;
        }

        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $postings = Postings::findOrFail($id);
        return view("backend.blog.edit", compact("postings"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\PostRequest $request, $id)
    {
        $postings = Postings::findOrFail($id);
        $gambarLama = $postings->image;
        $data = $this->handleRequest($request);
        $postings->update($data);

        if($gambarLama !== $postings->image){
            $this->removeImage($gambarLama);
        }

        $notification = array(
            'message' => 'Data berhasil diubah', 
            'alert-type' => 'success'
        );

        return redirect('/backend/blog')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Postings::findOrFail($id)->delete();

        $notification = array(
            'message' => $id, 
            'alert-type' => 'trash-message',
        );

        return redirect()->back()->with($notification);
    }

    public function restore($id)
    {
        $postings = Postings::withTrashed()->findOrFail($id);
        $postings->restore();

        $notification = array(
            'message' => 'Data berhasil di kembalikan', 
            'alert-type' => 'success',
        );

        return redirect()->back()->with($notification);
    }

    public function forceDestroy($id)
    {
        $postings = Postings::withTrashed()->findOrFail($id);
        $postings->forceDelete();

        $this->removeImage($postings->image);

        $notification = array(
            'message' => 'Data berhasil di hapus permanen', 
            'alert-type' => 'success',
        );

        return redirect()->back()->with($notification);
    }

    public function removeImage($image)
    {
        if(!empty($image))
        {
            $imagePath = $this->uploadPath . '/' . $image;
            $ekstensi = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ekstensi}", "_thumbnail.{$ekstensi}", $image);
            $thumbnailPath = $this->uploadPath . '/' .$thumbnail;

            if(file_exists($imagePath)) unlink($imagePath);
            if(file_exists($thumbnailPath)) unlink($thumbnailPath);
        }
    }
}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Category;
use App\Postings;

class CategoriesController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('posts')->orderBy('title')->get();

        return view("backend.categories.index", compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category();
        return view("backend.categories.create", compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\CategoryStoreRequest $request)
    {
        Category::create($request->all());

        $notification = array(
            'message' => 'Data berhasil disimpan',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view("backend.categories.edit", compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\CategoryUpdateRequest $request, $id)
    {
        Category::findOrFail($id)->update($request->all());

        $notification = array(
            'message' => 'Data berhasil diubah',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\CategoryDestroyRequest $request, $id)
    {
        $category = Category::findOrFail($id);
        Postings::withTrashed()->where('category_id', $id)->update(['category_id' => config('cms.default_category_idnya') ]);
        $category->delete();

        $notification = array(
            'message' => 'Data berhasil di hapus',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\User;
use App\Postings;
use App\Category;
use App\Prestasi;

class HomeController extends BackendController
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
    	$userCount = User::all()->count();
    	$postingsCount = Postings::all()->count();
    	$kategoriCount = Category::all()->count();
    	$prestasiCount = Prestasi::all()->count();

        return view('backend.home', compact('userCount', 'postingsCount', 'kategoriCount', 'prestasiCount'));
    }
}

app/Http/Controllers/Backend/JurusanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Jurusan;

class JurusanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $daftarjurusan = Jurusan::all();

        return view("backend.jurusan.index", compact('daftarjurusan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $daftarjurusan = new Jurusan();
        return view("backend.jurusan.create", compact('daftarjurusan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\JurusanRequest $request)
    {
        Jurusan::create($request->all());

        $notification = array(
            'message' => 'Data berhasil disimpan',
            'alert-type' => 'success'
        );

        return redirect("/backend/jurusan")->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $daftarjurusan = Jurusan::findOrFail($id);

        return view("backend.jurusan.edit", compact('daftarjurusan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\JurusanRequest $request, $id)
    {
        Jurusan::findOrFail($id)->update($request->all());

        $notification = array(
            'message' => 'Data berhasil diubah',
            'alert-type' => 'success'
        );

        return redirect("/backend/jurusan")->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Jurusan::findOrFail($id)->delete();

        $notification = array(
            'message' => 'Data berhasil di hapus',
            'alert-type' => 'success'
        );

        return redirect()->back()->with($notification);
    }
}

resources/views/backend/users/create.blade.php
@extends('layout.backend.utama')

@section('konten')
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">User</h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
                            <li class="breadcrumb-item active">Tambah Baru</li>
                        </ol>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row">
	            <div class="col-12">
	            	<div class="card">
                	    <div class="card-body">
                	        <h4 class="card-title">Data</h4>
                	        <h6 class="card-subtitle">Tambah untuk data User.</h6>
                	        {!! Form::model($user, [
                                    'method' => 'POST',
                                    'route' => 'users.store',
                                    'class' => 'form-material m-t-40',
                                    'files' => TRUE,
                                    'id' => 'user-form'
                                ])
                            !!}

                            @include('backend.users.form')
                            
                            {!! Form::close() !!}
                	    </div>
	            	</div>
	            </div>
        	</div>
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
    </div>
@endsection

resources/views/backend/users/edit.blade.php
@extends('layout.backend.utama')

@section('konten')
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">User</h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
                            <li class="breadcrumb-item active">Edit User</li>
                        </ol>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row">
	            <div class="col-12">
	            	<div class="card">
                	    <div class="card-body">
                	        <h4 class="card-title">Data</h4>
                	        <h6 class="card-subtitle">Edit data User.</h6>
                	        {!! Form::model($user, [
                                    'method' => 'PUT',
                                    'route' => ['users.update', $user->id],
                                    'class' => 'form-material m-t-40',
                                    'files' => TRUE,
                                    'id' => 'user-form'
                                ])
                            !!}

                            @include('backend.users.form')
                            
                            {!! Form::close() !!}
                	    </div>
	            	</div>
	            </div>
        	</div>
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
    </div>
@endsection

resources/views/backend/users/form.blade.php
<form class="form-material m-t-40">
    <div class="form-group {{ $errors->has('name') ? 'has-danger' : '' }}">
        {!! Form::label('name', 'Nama') !!}
        {!! Form::text('name', null, ['class' => 'form-control form-control-line']) !!}

        @if($errors->has('name'))
            <small class="form-control-feedback">{{ $errors->first('name') }}</small>
        @endif
    </div>

    <div class="form-group {{ $errors->has('email') ? 'has-danger' : '' }}">
        {!! Form::label('email', 'Email') !!}
        {!! Form::text('email', null, ['class' => 'form-control form-control-line']) !!}

        @if($errors->has('email'))
            <small class="form-control-feedback">{{ $errors->first('email') }}</small>
        @endif
    </div>

    <div class="form-group {{ $errors->has('password') ? 'has-danger' : '' }}">
        {!! Form::label('password', 'Password') !!}
        {!! Form::password('password', ['class' => 'form-control form-control-line']) !!}

        @if($errors->has('password'))
            <small class="form-control-feedback">{{ $errors->first('password') }}</small>
        @endif
    </div>

    {!! Form::button('<i class="icon-check"></i> Simpan', ['type' => 'submit', 'class' => 'btn waves-effect waves-light btn-outline-success'] )  !!}
</form>

resources/views/backend/users/index.blade.php
@extends('layout.backend.utama')

@section('konten')
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">User</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
                        <li class="breadcrumb-item active">Daftar User</li>
                    </ol>
                    <!--<a href="{{ route('users.create') }}" type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="icon-plus"></i> Tambah Data</a>-->
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Data</h4>
                    <h6 class="card-subtitle">Daftar semua data User.</code></h6>
                    <div class="table-responsive">
                        <table id="tableUser" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>No HP</th>
                                    <th>Alamat</th>
                                    <th>Biodata</th>
                                    <th>Role</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->no_hp }}</td>
                                    <td>{{ $user->alamat }}</td>
                                    <td>{{ $user->bio }}</td>
                                    <td>Role</td>
                                    <td>
                                        @if($user->id != 1 && $user->id != 2)

                                        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#confirmModal" data-whatever="@mdo"><i class="icon-trash"></i> Hapus</button>
                                        <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel1">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title text-danger" id="confirmModalLabel1">KONFIRMASI</h4>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <h4 class="text-danger">Apakah anda yakin akan menghapus User tersebut?</h4>
                                                        <br>
                                                        {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id]]) !!}

                                                        <div class="custom-control custom-checkbox">
                                                            <input type="checkbox" class="custom-control-input" id="hapusSemua" name="hapusSemua" value="hapusSemua">
                                                            <label class="custom-control-label text-danger" for="hapusSemua">Hapus beserta Blog yang terkait dengan User tersebut</label>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-danger">Ya</button>
                                                    </div>
                                                    {!! Form::close() !!}
                                                </div>
                                            </div>
                                        </div>
                                        @endif
                                        <a href="{{ route('users.edit', $user->id) }}" type="button" class="btn btn-outline-info"><i class="icon-note"></i> Edit</a>

                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>-->
    @foreach($users as $user)
    <div class="col-lg-4 col-md-6">
        <!-- Card -->
        <div class="card" style="padding: 50px 50px 50px 50px;">
            <img class="card-img-top img-responsive" src="{{ asset('backend/assets/images/users/user.png') }}" alt="Card image cap">
            <div class="card-body">
                <h4 class="card-title">{{ $user->name }}</h4>
                <p class="card-text"><i class="icon-envelope-open"></i> {{ $user->email }}</p>
                <p class="card-text"><i class="icon-phone"></i> {{ $user->no_hp }}</p>
                <p class="card-text"><i class="icon-location-pin"></i> {{ $user->alamat }}</p>
                <p class="card-text"><i class="icon-notebook"></i> {{ $user->bio }}</p>
                <a href="{{ route('users.edit', $user->id) }}" type="button" class="btn btn-outline-info"><i class="icon-note"></i> Edit</a>
            </div>
        </div>
        <!-- Card -->
    </div>
    @endforeach
</div>
</div>
<!-- ============================================================== -->
<!-- End Container fluid  -->
<!-- ============================================================== -->
</div>
@endsection

@include('backend.partials.message')