routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');

Route::get('/', [
	'uses' => 'BlogController@index',
	'as' => 'blog',
]);

Route::get('/berita/{postings}', [
	'uses' => 'BlogController@tampil',
	'as' => 'blog.tampil',
]);

Route::get('/category/{category}', [
	'uses' => 'BlogController@kategori',
	'as' => 'category',
]);

Route::get('/berita', [
	'uses' => 'BlogController@berita',
	'as' => 'blog.berita',
]);

Route::get('/author/{author}', [
	'uses' => 'BlogController@author',
	'as' => 'author',
]);

Route::put('/backend/blog/restore/{blog}', [
	'as' => 'backend.blog.restore',
	'uses' => 'Backend\BlogController@restore',
]);

Route::delete('/backend/blog/force-destroy/{blog}', [
	'as' => 'backend.blog.force-destroy',
	'uses' => 'Backend\BlogController@forceDestroy',
]);

Route::put('/backend/prestasi/restore/{prestasi}', [
	'as' => 'backend.prestasi.restore',
	'uses' => 'Backend\PrestasiController@restore',
]);

Route::delete('/backend/prestasi/force-destroy/{prestasi}', [
	'as' => 'backend.prestasi.force-destroy',
	'uses' => 'Backend\PrestasiController@forceDestroy',
]);

Route::resource('/backend/blog', 'Backend\BlogController');

Route::resource('/backend/prestasi', 'Backend\PrestasiController');

Route::resource('/backend/categories', 'Backend\CategoriesController');

Route::resource('/backend/users', 'Backend\UsersController');

Route::resource('/backend/jurusan', 'Backend\JurusanController');

Route::resource('/backend/profil', 'Backend\ProfilController');

app/Prestasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;

class Prestasi extends Model
{
    use SoftDeletes;

    public $table = "prestasi";
    
	protected $dates = ['published_at'];
    protected $fillable = ['title','slug','oleh','body','published_at', 'image','tingkat'];

	public function Author()
	{
		return $this->belongsTo(User::class);
	}

    public function getImageUrlAttribute($value)
    {
    	$gambarUrl = "";

    	if(!is_null($this->image)){
            $directory = config('cms.image.directory');
    		$gambarPath = public_path(). "/{$directory}/" . $this->image;
    		if(file_exists($gambarPath)){
    			$gambarUrl = asset("{$directory}/" . $this->image);
    		}
    	}

    	return $gambarUrl;
    }

    public function getImageThumbUrlAttribute($value)
    {
        
        $gambarUrl = "";

        if(!is_null($this->image)){
            $directory = config('cms.image.directory');
            $ekstensi = substr(strchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ekstensi}", "_thumb.{$ekstensi}", $this->image);
            $gambarPath = public_path(). "/{$directory}/" . $thumbnail;
            if(file_exists($gambarPath)){
                $gambarUrl = asset("{$directory}/" . $thumbnail);
            }
        }

        return $gambarUrl;
    }

    public function getDateAttribute($value)
    {
    	return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function scopeLatestFirst()
    {
    	return $this->orderBy('published_at', 'DESC');
    }

    public function scopePopular()
    {
        return $this->orderBy('view_count', 'DESC');
    }

    public function scopePublished()
    {
    	return $this->where("published_at", "<=", Carbon::now());
    }

    public function getBodyHtmlAttribute($value)
    {
    	return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }

    public function getExcerptHtmlAttribute($value)
    {
    	return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
    }

    public function dateFormatted($showTimes = false)
    {
        $format = "d/m/Y";
        if($showTimes) $format = $format . " H:i:s";
        return $this->created_at->format($format);
    }

    public function publicationLabel()
    {
        if(! $this->published_at){
            return '<span class="badge badge-warning">Draft</span>';
        }elseif($this->published_at && $this->published_at->isFuture()){
            return '<span class="badge badge-info">Terjadwal</span>';
        }else{
            return '<span class="badge badge-success">Dipublikasikan</span>';
        }
    }

    public function setPublishedAtAttribute($value)
    {
        $this->attributes['published_at'] = $value ?: NULL;
    }

    public function scopeScheduled($query)
    {
        return $query->where("published_at", ">", Carbon::now());   
    }

    public function scopeDraft($query)
    {
        return $query->whereNull("published_at");
    }

}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check-permission');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Postings;
use Intervention\Image\Facades\Image;

class BlogController extends BackendController
{
    protected $uploadPath;

    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = public_path(config('cms.image.directory'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $postings = Postings::with('category')->with('author')->latestFirst()->get();

        $postingsTrash = Postings::with('category')->with('author')->latestFirst()->onlyTrashed()->get();

        $postingsPublished = Postings::with('category')->with('author')->latestFirst()->published()->get();

        $postingsDrafted = Postings::with('category')->with('author')->latestFirst()->draft()->get();

        $postingsScheduled = Postings::with('category')->with('author')->latestFirst()->scheduled()->get();

        return view("backend.blog.index", compact('postings', 'postingsTrash','postingsScheduled','postingsDrafted','postingsPublished'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Postings $postings)
    {
        return view("backend.blog.create", compact('postings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\PostRequest $request)
    {
        $data = $this->handleRequest($request);

        $request->user()->posts()->create($data);

        $notification = array(
            'message' => 'Data berhasil disimpan', 
            'alert-type' => 'success'
        );

        return redirect('/backend/blog')->with($notification);
    }

    public function handleRequest($request)
    {
        $data = $request->all();

        if($request->hasFile('image'))
        {
            $width = config('cms.image.thumbnail.width');
            $height = config('cms.image.thumbnail.height');
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $destination = $this->uploadPath;

            $successUploaded = $image->move($destination, $fileName);

            if($successUploaded)
            {
                $ekstensi = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$ekstensi}", "_thumbnail.{$ekstensi}", $fileName);
                Image::make($destination . '/' . $fileName)->resize($width, $height)->save($destination . '/' . $thumbnail);
            }

            $data['image'] = $fileName;
        }

        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $postings = Postings::findOrFail($id);
        return view("backend.blog.edit", compact("postings"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\PostRequest $request, $id)
    {
        $postings = Postings::findOrFail($id);
        $gambarLama = $postings->image;
        $data = $this->handleRequest($request);
        $postings->update($data);

        if($gambarLama !== $postings->image){
            $this->removeImage($gambarLama);
        }

        $notification = array(
            'message' => 'Data berhasil diubah', 
            'alert-type' => 'success'
        );

        return redirect('/backend/blog')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Postings::findOrFail($id)->delete();

        $notification = array(
            'message' => $id, 
            'alert-type' => 'trash-message',
        );

        return redirect()->back()->with($notification);
    }

    public function restore($id)
    {
        $postings = Postings::withTrashed()->findOrFail($id);
        $postings->restore();

        $notification = array(
            'message' => 'Data berhasil di kembalikan', 
            'alert-type' => 'success',
        );

        return redirect()->back()->with($notification);
    }

    public function forceDestroy($id)
    {
        $postings = Postings::withTrashed()->findOrFail($id);
        $postings->forceDelete();

        $this->removeImage($postings->image);

        $notification = array(
            'message' => 'Data berhasil di hapus permanen', 
            'alert-type' => 'success',
        );

        return redirect()->back()->with($notification);
    }

    public function removeImage($image)
    {
        if(!empty($image))
        {
            $imagePath = $this->uploadPath . '/' . $image;
            $ekstensi = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ekstensi}", "_thumbnail.{$ekstensi}", $image);
            $thumbnailPath = $this->uploadPath . '/' .$thumbnail;

            if(file_exists($imagePath)) unlink($imagePath);
            if(file_exists($thumbnailPath)) unlink($thumbnailPath);
        }
    }
}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Category;
use App\Postings;

class CategoriesController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('posts')->orderBy('title')->get();

        return view("backend.categories.index", compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category();
        return view("backend.categories.create", compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\CategoryStoreRequest $request)
    {
        Category::create($request->all());

        $notification = array(
            'message' => 'Data berhasil disimpan',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view("backend.categories.edit", compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\CategoryUpdateRequest $request, $id)
    {
        Category::findOrFail($id)->update($request->all());

        $notification = array(
            'message' => 'Data berhasil diubah',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\CategoryDestroyRequest $request, $id)
    {
        $category = Category::findOrFail($id);
        Postings::withTrashed()->where('category_id', $id)->update(['category_id' => config('cms.default_category_idnya') ]);
        $category->delete();

        $notification = array(
            'message' => 'Data berhasil di hapus',
            'alert-type' => 'success'
        );

        return redirect("/backend/categories")->with($notification);
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\User;
use App\Postings;
use App\Category;
use App\Prestasi;

class HomeController extends BackendController
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
    	$userCount = User::all()->count();
    	$postingsCount = Postings::all()->count();
    	$kategoriCount = Category::all()->count();
    	$prestasiCount = Prestasi::all()->count();

        return view('backend.home', compact('userCount', 'postingsCount', 'kategoriCount', 'prestasiCount'));
    }
}

app/Http/Controllers/Backend/JurusanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Jurusan;

class JurusanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $daftarjurusan = Jurusan::all();

        return view("backend.jurusan.index", compact('daftarjurusan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $daftarjurusan = new Jurusan();
        return view("backend.jurusan.create", compact('daftarjurusan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\JurusanRequest $request)
    {
        Jurusan::create($request->all());

        $notification = array(
            'message' => 'Data berhasil disimpan',
            'alert-type' => 'success'
        );

        return redirect("/backend/jurusan")->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $daftarjurusan = Jurusan::findOrFail($id);

        return view("backend.jurusan.edit", compact('daftarjurusan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\JurusanRequest $request, $id)
    {
        Jurusan::findOrFail($id)->update($request->all());

        $notification = array(
            'message' => 'Data berhasil diubah',
            'alert-type' => 'success'
        );

        return redirect("/backend/jurusan")->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Jurusan::findOrFail($id)->delete();

        $notification = array(
            'message' => 'Data berhasil di hapus',
            'alert-type' => 'success'
        );

        return redirect()->back()->with($notification);
    }
}

resources/views/backend/prestasi/form.blade.php
<form class="form-material m-t-40">
    <div class="form-group {{ $errors->has('title') ? 'has-danger' : '' }}">
        {!! Form::label('title', 'Judul') !!}
        {!! Form::text('title', null, ['class' => 'form-control form-control-line']) !!}

        @if($errors->has('title'))
            <small class="form-control-feedback">{{ $errors->first('title') }}</small>
        @endif
    </div>

    <div class="form-group {{ $errors->has('slug') ? 'has-danger' : '' }}">
        {!! Form::label('slug', 'Slug') !!}
        {!! Form::text('slug', null, ['class' => 'form-control form-control-line']) !!}

        @if($errors->has('slug'))
            <small class="form-control-feedback">{{ $errors->first('slug') }}</small>
        @endif
    </div>

    <div class="form-group {{ $errors->has('oleh') ? 'has-danger' : '' }}">
        {!! Form::label('oleh', 'Dimenangkan Oleh') !!}
        {!! Form::text('oleh', null, ['class' => 'form-control form-control-line']) !!}

        @if($errors->has('oleh'))
            <small class="form-control-feedback">{{ $errors->first('oleh') }}</small>
        @endif
    </div>

    <div class="form-group {{ $errors->has('body') ? 'has-danger' : '' }}">
        {!! Form::label('body', 'Isi') !!}
        {!! Form::text('body', null, ['class' => 'form-control form-control-line']) !!}

        @if($errors->has('body'))
            <small class="form-control-feedback">{{ $errors->first('body') }}</small>
        @endif
    </div>

    <div class="form-group">
        {!! Form::label('published_at', 'Tanggal Publikasi') !!}
        {!! Form::text('published_at', null, ['class' => 'form-control', 'id' => 'tgl']) !!}
    </div>

    <div class="form-group {{ $errors->has('tingkat') ? 'has-danger' : '' }}">
        {!! Form::label('tingkat', 'Tingkat') !!}
        {!! Form::select('tingkat', ['Nasional' => 'Nasional', 'Provinsi' => 'Provinsi', 'Kabupaten' => 'Kabupaten'], null, ['class' => 'form-control form-control-line',
         'placeholder' => 'Pilih Tingkat']) !!}

         @if($errors->has('tingkat'))
            <small class="form-control-feedback">{{ $errors->first('tingkat') }}</small>
        @endif
    </div>

    <div class="form-group {{ $errors->has('image') ? 'has-danger' : '' }}">
        {!! Form::label('image', 'Gambar') !!}
        {!! Form::file('image', ['class' => 'dropify', 'data-default-file' => "{{ ($prestasi->image_thumb_url) ? $prestasi->image_thumb_url : '' }}"]) !!}

         @if($errors->has('image'))
            <small class="form-control-feedback">{{ $errors->first('image') }}</small>
        @endif
    </div>

    {!! Form::button('<i class="icon-check"></i> Simpan', ['type' => 'submit', 'class' => 'btn waves-effect waves-light btn-outline-success'] )  !!}
</form>

resources/views/backend/prestasi/index.blade.php
@extends('layout.backend.utama')

@section('konten')
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">Prestasi</h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Prestasi</a></li>
                            <li class="breadcrumb-item active">Semua Prestasi</li>
                        </ol>
                        <a href="{{ route('prestasi.create') }}" type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="icon-plus"></i> Tambah Data</a>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Data</h4>
                            <h6 class="card-subtitle">Daftar semua data Prestasi.</code></h6>
                            <!-- Nav tabs -->
                            <div class="vtabs customvtab">
                                <ul class="nav nav-tabs tabs-vertical" role="tablist">
                                    <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#utama" role="tab"><span class="hidden-sm-up"><i class="ti-home"></i></span> <span class="hidden-xs-down">Utama</span> </a> </li>
                                    <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#tempatsampah" role="tab"><span class="hidden-sm-up"><i class="icon-trash"></i></span> <span class="hidden-xs-down">Tempat Sampah</span></a> </li>
                                </ul>
                                <!-- Tab panes -->
                                <div class="tab-content" style="width: 100%;">
                                    <div class="tab-pane active" id="utama" role="tabpanel">
                                        <div class="table-responsive">
                                            <table id="tableUtamaPrestasi" class="table table-bordered table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Judul Prestasi</th>
                                                        <th>Tingkat</th>
                                                        <th>Dimenangkan</th>
                                                        <th>Isi</th>
                                                        <th>Tanggal</th>
                                                        <th>Aksi</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($prestasi as $post)
                                                        <tr>
                                                            <td>{{ $post->title }}</td>
                                                            <td>{{ $post->tingkat }}</td>
                                                            <td>{{ $post->oleh }}</td>
                                                            <td>{{ $post->body }}</td>
                                                            <td>
                                                                <abbr title="{{ $post->dateFormatted(true) }}"> {{ $post->dateFormatted() }}
                                                                </abbr>
                                                                &nbsp;&nbsp;
                                                                {!! $post->publicationLabel() !!}
                                                            </td>
                                                            <td>
                                                                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#confirmModal" data-whatever="@mdo"><i class="icon-trash"></i> Hapus</button>
                                                                <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel1">
                                                                    <div class="modal-dialog" role="document">
                                                                        <div class="modal-content">
                                                                            <div class="modal-header">
                                                                                <h4 class="modal-title text-danger" id="confirmModalLabel1">KONFIRMASI</h4>
                                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                                            </div>
                                                                            <div class="modal-body">
                                                                                <h4 class="text-danger">Apakah anda yakin akan menghapus Prestasi tersebut?</h4>
                                                                                <br>
                                                                                {!! Form::open(['method' => 'DELETE', 'route' => ['prestasi.destroy', $post->id]]) !!}
                                                                            </div>
                                                                            <div class="modal-footer">
                                                                                <button type="submit" class="btn btn-danger">Ya</button>
                                                                            </div>
                                                                                {!! Form::close() !!}
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <a href="{{ route('prestasi.edit', $post->id) }}" type="button" class="btn btn-outline-info"><i class="icon-note"></i> Edit</a>
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="tempatsampah" role="tabpanel">
                                        <div class="table-responsive">
                                            <table id="tableTrashPostings" class="table table-bordered table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Judul Prestasi</th>
                                                        <th>Dimenangkan</th>
                                                        <th>Isi</th>
                                                        <th>Tanggal</th>
                                                        <th>Aksi</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($prestasiTrash as $posts)
                                                        <tr>
                                                            <td>{{ $posts->title }}</td>
                                                            <td>{{ $posts->oleh }}</td>
                                                            <td>{{ $posts->body }}</td>
                                                            <td>
                                                                <abbr title="{{ $posts->dateFormatted(true) }}"> {{ $posts->dateFormatted() }}
                                                                </abbr>
                                                            </td>
                                                            <td>
                                                        {!! Form::open(['method' => 'PUT', 'route' => ['backend.prestasi.restore', $posts->id]]) !!}

                                                                <button type="submit" class="btn btn-outline-primary"><i class="icon-reload"></i> Kembalikan</button>

                                                        {!! Form::close() !!}
                                                        &nbsp;
                                                        {!! Form::open(['method' => 'DELETE', 'route' => ['backend.prestasi.force-destroy', $posts->id]]) !!}

                                                                <button type="submit" class="btn btn-outline-danger"><i class="icon-close" onclick="return confirm('Anda yakin akan menghapus permanen?')"></i> Hapus Permanen</button>

                                                        {!! Form::close() !!}
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        	</div>
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
    </div>
@endsection

@include('backend.partials.message')